name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          orjson-version: ["3.8.3", "3.8.4", "3.8.5"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.14

      - name: Install
        run: |
          pip install orjson==${{ matrix.orjson-version }}
          pip install pytest pytest-benchmark

      - name: Test
        run: pytest test_orjson_dumps.py > sample.txt

      - name: Report
        run: |
          set +e
          echo "## ORJSON ${{ matrix.orjson-version }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat sample.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
