name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          orjson-version: ["3.8.3", "3.8.4", "3.8.5"]
          python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install orjson==${{ matrix.orjson-version }}
          pip install pytest pytest-benchmark pytest-memray

      - name: Test
        run: pytest test_orjson_dumps.py --memray > sample.txt

      - name: Write Summary
        run: |
          set +e
          echo "## ORJSON ${{ matrix.orjson-version }} Py ${{ matrix.python-version }}" >> orjson_${{ matrix.orjson-version }}_py_${{ matrix.python-version }}.md
          echo '```' >> orjson_${{ matrix.orjson-version }}_py_${{ matrix.python-version }}.md
          cat sample.txt >> orjson_${{ matrix.orjson-version }}_py_${{ matrix.python-version }}.md
          echo '```' >> orjson_${{ matrix.orjson-version }}_py_${{ matrix.python-version }}.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: "pytest_res"
          path: orjson_${{ matrix.orjson-version }}_py_${{ matrix.python-version }}.md

  summary:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: "pytest_res"
          path: ""

      - name: Summary
        run: cat orjson*.md > $GITHUB_STEP_SUMMARY
